# Generated by Django 3.2.9 on 2021-12-07 13:28

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0012_auto_20211130_1602'),
    ]

    operations = [
        migrations.CreateModel(
            name='Postall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('newimage', cloudinary.models.CloudinaryField(max_length=255, null=True, verbose_name='image')),
            ],
        ),
    ]
